### ISSUE TITLE
Portals Not Initializing

### ISSUE THREAD

**Issue by droidforensics** [digitalsleuth/WIN-FOR#9]
Hello! First off, thanks for this wonderful tool - I've been using it for about 6 months now and it's so incredibly helpful.

I'm having one minor problem: the `Portals` app doesn't seem to install and configure itself correctly. As far as I can tell, all other applications did, but Portals seems to be an exception.

The application doesn't get licensed (which I think it should? Based on the [salt state](https://github.com/digitalsleuth/winfor-salt/blob/fd0b4caa2d3364a9207f112e639f85eb63fdae75/winfor/files/license.ptl#L3)?) and also doesn't configure any of the Portals.

[Here's the debug log](https://gist.github.com/droidforensics/4d4b877ab9b203cfa59db3ec55a699ef) - interestingly I see it trying to reference `C:\Users\Public` though my user is `forensics` so I'd think it'd be `C:\Users\forensics`? This debug log is generated from me unselecting all applications in WIN-FOR Customizer, then selecting `Portals` by itself, and installing.

And some computer info [here](https://gist.github.com/droidforensics/31e4f930d8886867e1d86f6a49299881). The OS version is 23H2, build 22631.4317.

Any help is appreciated! Thank you so much for everything you do.

![image](https://github.com/user-attachments/assets/181e718c-2e3a-4db1-89a7-e7b37247ed14)

**Comment by digitalsleuth** [comment]
Hi @droidforensics , I'm glad you like Win-FOR! The reason you're experiencing this is because the option to simply install Portals doesn't add any customization or themes, hence why the Portals window is empty.  

The entries for `C:\Users\Public` are there based on the [`cleanup\desktop-folders.sls`](https://github.com/digitalsleuth/winfor-salt/blob/main/winfor/cleanup/desktop-folders.sls) state, which will check to see if Portals is installed and, if not, place a copy of the folders which contain the shortcuts for Portals onto the `Public` desktop so all users (including the current) have access to all of the shortcuts without Portals. In this instance, Portals was installed, so the state ran and assessed that nothing needed to be copied to the `Public` desktop. The entries you see are the evaluation of the requirements, not an actual copy itself.

If you do want Portals configured with the installed applications, you would have to select other applications to install, and ensure you select the `Themed` option from Win-FOR and select `WIN-FOR`. This will also apply a system-wide theme for Win-FOR. Only those applications which get installed will have an entry in Portals, so if you don't select any, and still select the `Themed` option, it will only apply the system theme, but not affect Portals.

I hope that helps clear things up. Let me know if you have any other questions or concerns.

Cheers!

**Comment by droidforensics** [comment]
Hi @digitalsleuth! Sorry I left you hanging for a week, work's been busy and I just got around to rebuilding a completely clean VM today.

Thanks a ton for your explanation! That helps a lot. Salt is completely new to me so I'll have to poke around the states to try and learn more, it's great tech!

Anyway, I rebuilt my VM earlier this evening (using `v10.0.0`) and selected the `Themed` option as you suggested, it worked as expected! I have yet to install the WSL VMs but I'll open another issue if something goes awry there.  🙂 

I'll go ahead and close this issue with this comment. 

Thanks again, and take care,
Droid/Jackson
